esphome:
    name: ${name}
    friendly_name: ${long_name}
    name_add_mac_suffix: true

logger:
api:
    encryption:
        key: !secret api_encryption

ota:
    - platform: esphome
      password: !secret ota_password

sensor:
    - platform: internal_temperature
      id: system_internal_temperature
      name: Internal Temperature
      icon: mdi:oil-temperature
      entity_category: diagnostic
      device_class: "temperature"
      unit_of_measurement: "°C"

    - platform: uptime
      id: system_uptime
      name: Device Uptime
      icon: mdi:power-settings
      update_interval: 30s
      entity_category: diagnostic
      state_class: total_increasing
      disabled_by_default: true

button:
    - platform: safe_mode
      id: system_safe_mode
      name: Enter safe mode
      icon: mdi:alert
      entity_category: diagnostic

    - platform: restart
      id: system_restart
      name: Restart device
      icon: mdi:reload
      entity_category: config

    - platform: shutdown
      id: system_shutdown
      name: Shutdown
      icon: mdi:power
      entity_category: config
      disabled_by_default: true

    - platform: factory_reset
      id: factory_reset_btn
      name: Factory reset
      entity_category: diagnostic
